package model;

public enum OrderState {
    NUEVO,
    VALIDADO,
    DISPONIBILIDAD_CONFIRMADA,
    SUBTOTAL_CALCULADO,
    REVISION_FRAUDE,
    DESCUENTO_APLICADO,
    IMPUESTOS_CALCULADOS,
    CONFIRMADO,
    RECHAZADO
}
